# Generated by Django 4.1.3 on 2022-12-03 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='fio',
        ),
        migrations.RenameField(
            model_name='coauthor',
            old_name='name',
            new_name='fio',
        ),
        migrations.RemoveField(
            model_name='author',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='author',
            name='surname',
        ),
        migrations.RemoveField(
            model_name='coauthor',
            name='patronymic',
        ),
        migrations.RemoveField(
            model_name='coauthor',
            name='surname',
        ),
        migrations.AddField(
            model_name='application',
            name='photo',
            field=models.FileField(default=None, upload_to='photos'),
            preserve_default=False,
        ),
    ]
