# Generated by Django 4.1.3 on 2022-12-03 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0003_delete_application_delete_author_delete_coauthor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=99)),
            ],
        ),
        migrations.CreateModel(
            name='CoAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('organization', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('heading', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=100)),
                ('annotation', models.TextField()),
                ('file', models.FileField(upload_to='files')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('accepted', 'Одобрено'), ('rejected', 'Отклонено')], default='new', max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('links', models.TextField(blank=True)),
                ('photo', models.FileField(blank=True, upload_to='photos')),
                ('rating', models.IntegerField(blank=True, default=0)),
                ('votes', models.IntegerField(blank=True, default=0)),
                ('coauthors', models.ManyToManyField(blank=True, to='main.coauthor')),
                ('main_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.author')),
            ],
        ),
    ]
