# Generated by Django 4.1.3 on 2022-12-03 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='rating',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
