# Generated by Django 4.1.3 on 2022-12-04 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_application_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('video', 'Видео'), ('article', 'Статья'), ('downgrade', 'Снижение')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Stage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField(blank=True, max_length=30)),
                ('H', models.CharField(blank=True, max_length=20)),
                ('P', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ExpertMark',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('value', models.IntegerField()),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.application')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.expert')),
                ('mark', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mark')),
            ],
        ),
        migrations.CreateModel(
            name='Contests',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('new', 'Новый'), ('old', 'Старый'), ('now', 'Текущий')], default='new', max_length=10)),
                ('page_heading', models.CharField(blank=True, max_length=100)),
                ('heading_0', models.CharField(blank=True, max_length=100)),
                ('heading_1', models.CharField(blank=True, max_length=100)),
                ('heading_2', models.CharField(blank=True, max_length=100)),
                ('about_contest', models.TextField(blank=True)),
                ('participate_info', models.TextField(blank=True)),
                ('registration_is_available', models.BooleanField(default=False)),
                ('registration_info', models.TextField(blank=True)),
                ('viewing_works', models.BooleanField(default=False)),
                ('results', models.BooleanField(default=False)),
                ('stages', models.ManyToManyField(to='main.stage')),
            ],
        ),
    ]
