# Generated by Django 4.1.3 on 2022-12-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_expert_mark_stage_expertmark_contests'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='registration_info',
        ),
        migrations.AddField(
            model_name='contests',
            name='participate_info_available',
            field=models.BooleanField(default=False),
        ),
    ]
