# Generated by Django 4.1.3 on 2022-12-04 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_contests_registration_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert',
            name='login',
            field=models.CharField(default='', max_length=100, unique=True),
        ),
    ]
