# Generated by Django 4.1.3 on 2022-12-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contests_uid_antiplagiat_alter_mark_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contests',
            name='uid_antiplagiat',
        ),
        migrations.AddField(
            model_name='application',
            name='uid_antiplagiat',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
